name: deploy
true: 
  workflow_dispatch: 
    inputs: 
      deployment_notes: 
        description: "Deployment notes"
        required: true
on: [push, pull_request]
# Trigger the workflow on push or pull request,
# branches:
#   - development
jobs:
  deploy:
    name: "Deploy (developement)"
    runs-on: ubuntu-latest
    env:
      TARGET_ENV: "production"
      SERVERIP: ${{ secrets.DEV_SERVERIP }}
      SSHKEY: ${{ secrets.DEV_SSHKEY }}
      USERNAME: ${{ secrets.DEV_USERNAME }}
    # run the deploy pipeline on master only
    if: github.ref == 'refs/heads/development'
    steps:
    - name: Nullcast | Check ssh
      run: |
        'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - name: Nullcast | Run deploy script
      run: |
        ssh-add <(echo "$SSHKEY" | tr -d '\r')
        ./scripts/dev_deploy.sh | ssh -o StrictHostKeyChecking=no $USERNAME@$SERVERIP
        echo "Deploy step finished"